"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Express = require("express");
var Helmet = require("helmet");
var routers_1 = require("./routers");
var server = Express();
server.use(Helmet());
server.use(Express.json());
// server.use('/api/projects', projectsRouter);
// server.use('/api/resources', resourcesRouter);
server.use('/api/tasks', routers_1.tasksRouter);
exports.default = server;
